import type { NextPage } from 'next'
import Head from 'next/head'
import {Login} from "../components/Login";
import styled from "styled-components";
import {useMoralis} from "react-moralis";
import {Header} from "../components/Header";
import {Messages} from "../components/Messages";

const Home: NextPage = () => {
    const { isAuthenticated} = useMoralis()

    if (!isAuthenticated) {
        return (
            <Login />
        )
    }

    return (
        <Container>
            <Head>
                <title>Metaverse app</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Page>
                <Header />
                <Messages />
            </Page>
        </Container>
    )
}

export default Home

const Container = styled.div`
  width: 100%;
  height: 100vh;
`

const Page = styled.div`
  width: 100%;
  height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: flex-start;
  background: #340534;
  color: white;
`