import type { NextPage } from 'next'
import Head from 'next/head'
import {Login} from "../components/Login";
import styled from "styled-components";
import {useMoralis} from "react-moralis";

const Home: NextPage = () => {
    const { isAuthenticated, logout } = useMoralis()

    const handleLogout = async () => {
        await logout()
    }

    if (!isAuthenticated) {
        return (
            <Login />
        )
    }

    return (
        <Container>
            <Head>
                <title>Metaverse app</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>metaverse</h1>
            <button onClick={handleLogout}>Logout</button>
        </Container>
    )
}

export default Home

const Container = styled.div`
  width: 100%;
  height: 100vh;
`